# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-json
    -   id: check-yaml
    -   id: check-toml
    -   id: debug-statements
    -   id: pretty-format-json
        args: ["--autofix", "--no-sort-keys"]
#-   repo: https://github.com/pre-commit/mirrors-isort
#    rev: master
#    hooks:
#    -   id: isort
-   repo: https://github.com/PyCQA/isort
    rev: '5.10.1'
    hooks:
    -    id: isort
         additional_dependencies:
         -   toml
-   repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: '0.0.2'
    hooks:
    -   id: stylelint
        additional_dependencies: ['stylelint', 'stylelint-config-standard']
-   repo: https://github.com/psf/black
    rev: '22.10.0'
    hooks:
    -   id: black
        language_version: python3.8
