language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
git:
  depth: false  # Disable clone depth - it is not needed yet
install:
  - pip install poetry
  - poetry install --no-interactions --verbose
script:
  - poetry run pytest
