name: tempren
title: tempren
summary: Template-based file renaming utility
base: core24
adopt-info: tempren
source-code: https://github.com/idle-code/tempren.git
description: |
  tempren is a powerful file renaming utility that uses flexible template expressions to generate names for your files.
  Tag templates can modify original filename, extract metadata from the files or anything in between.
  A rich library of built-in tags helps with working with many common file types out-of-the-box.
grade: stable
confinement: strict
platforms:
  amd64:
  arm64:
    build-on: [amd64, arm64]
    build-for: [arm64]

parts:
  tempren:
    plugin: python
    source: .
    override-pull: |
      craftctl default
      craftctl set version=$(cat "$CRAFT_PART_SRC/version.txt")
    python-packages:
      - "tempren[video]"
    stage-packages:
      - libmagic1
      - libmediainfo0v5

apps:
  tempren:
    command: bin/tempren
    plugs:
      - home
      - removable-media
