name: make-a-release
on:
  workflow_run:
    workflows: [ publish-on-pypi, publish-on-snapcraft ]
    types:
      - completed
jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make a GitHub release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
