name: Tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install MediaInfo library
        run: sudo apt-get install -y libmediainfo0v5
      - name: Install dependencies
        run: poetry install --no-interaction --no-root --extras video
      - name: Run unit tests
        run: poetry run pytest
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
      - name: Check types
        run: poetry run mypy
